apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: swaparoony-face-swap
  namespace: face-swapper
  annotations:
    serving.kserve.io/deploymentMode: "RawDeployment"
    serving.kserve.io/disable-initializer: "true"
spec:
  predictor:
    tolerations:
    - effect: NoSchedule
      key: nvidia.com/gpu
      operator: Exists
    volumes:
    - name: home
      emptyDir: {}
    containers:
    - name: kserve-container
      image: ghcr.io/thesteve0/swaparoony-kserve:latest
      env:
      - name: HOME
        value: /home/user
      ports:
      - containerPort: 8080
        protocol: TCP
      resources:
        requests:
          cpu: 500m
          memory: 5Gi
          nvidia.com/gpu: 1
        limits:
          cpu: 1000m
          memory: 10Gi
          nvidia.com/gpu: 1
      readinessProbe:
        httpGet:
          path: /v1/models/swaparoony-face-swap
          port: 8080
        initialDelaySeconds: 30
        periodSeconds: 10
      livenessProbe:
        httpGet:
          path: /v1/models/swaparoony-face-swap
          port: 8080
        initialDelaySeconds: 60
        periodSeconds: 303
      volumeMounts:
      - name: home
        mountPath: /home/user